#!/usr/bin/env bash
#
# clean.sh — remove temporary files and regenerable build output.
#
# Safe to run repeatedly (idempotent). Deletes:
#   - macOS .DS_Store metadata
#   - Hugo generated output (public/, resources/_gen/) — rebuilt by `hugo`
#   - Hugo build lock (.hugo_build.lock)
#   - Playwright MCP dev artifacts (.playwright-mcp/)
#   - stray editor temp files (*.swp, *~)
#
# It never touches git-tracked source. Generated output is gitignored and
# regenerated by `hugo --minify` (locally and in CI).
#
# Usage: bash scripts/clean.sh   (or ./scripts/clean.sh if executable)

set -euo pipefail

# Run from the repo root regardless of where the script is invoked.
if ROOT="$(git rev-parse --show-toplevel 2>/dev/null)" && [ -n "$ROOT" ]; then
  cd "$ROOT"
else
  cd "$(dirname "$0")/.."
  ROOT="$(pwd)"
fi

echo "Cleaning project at: $ROOT"

echo "→ Removing .DS_Store files"
find . -path ./.git -prune -o -name '.DS_Store' -type f -print -delete

echo "→ Removing Hugo generated output (public/, resources/_gen/)"
rm -rf public resources/_gen

echo "→ Removing Hugo build lock (.hugo_build.lock)"
rm -f .hugo_build.lock

echo "→ Removing Playwright MCP dev artifacts (.playwright-mcp/)"
rm -rf .playwright-mcp

echo "→ Removing stray editor temp files (*.swp, *~)"
find . -path ./.git -prune -o \( -name '*.swp' -o -name '*~' \) -type f -print -delete

echo "✓ Clean complete."
